#!/usr/bin/env zsh

set -e

if [ -f cidfile ] ; then
  podman start $(cat cidfile)
else

  MINECRAFT_VERSION=1.20.1
  FORGE_VERSION=47.4.0
  MONI_VERSION=0.12.9
  MONI_VERSION_TYPE=Release

  IMAGE_TAG=bingecraft.net/minecraft-server/$MINECRAFT_VERSION/forge/$FORGE_VERSION/moni:$MONI_VERSION

  podman build \
    --build-arg MINECRAFT_VERSION=$MINECRAFT_VERSION \
    --build-arg FORGE_VERSION=$FORGE_VERSION \
    --build-arg MONI_VERSION=$MONI_VERSION \
    --build-arg MONI_VERSION_TYPE=$MONI_VERSION_TYPE \
    --tag $IMAGE_TAG \
    .

  mkdir -p backups

  podman run \
    --cidfile cidfile \
    --detach \
    --interactive \
    --publish 25565:25565 \
    --tty \
    --volume $(readlink -f backups):/home/minecraft/backups:U \
    --volume $(readlink -f secrets):/home/minecraft/secrets \
    $IMAGE_TAG

fi

podman logs --follow $(cat cidfile)
