#!/usr/bin/env zsh

set -e

if [ -f cidfile ] ; then
  podman start $(cat cidfile)
else
  IMAGE_TAG=bingecraft-net/minecraft-server

  mkdir -p backups

  podman build -t $IMAGE_TAG .
  podman run -di \
    -p 8100:8100 \
    -p 25566:25565 \
    -v $(readlink -f backups):/home/minecraft/backups:U \
    -v $(readlink -f secrets):/home/minecraft/secrets \
    $IMAGE_TAG > cidfile
fi

podman logs --follow $(cat cidfile)
