#!/usr/bin/env zsh

set -e

if [ -f cidfile ] ; then
  podman start $(cat cidfile)
else
  IMAGE_TAG=bingecraft-net/minecraft-server/paper

  podman build \
    --build-arg MINECRAFT_VERSION=1.21.6 \
    --build-arg PAPER_VERSION=27 \
    --tag $IMAGE_TAG \
    .

  mkdir -p backups

  podman run \
    --cidfile cidfile \
    --detach \
    --interactive \
    --publish 8100:8100 \
    --publish 25565:25565 \
    --volume $(readlink -f backups):/home/minecraft/backups:U \
    --volume $(readlink -f secrets):/home/minecraft/secrets \
    $IMAGE_TAG
fi

podman logs --follow $(cat cidfile)
